import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Dict, Optional
from datetime import datetime

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from config import get_config
from utils import get_logger, retry_with_backoff

console = Console()


class EmailSender:
    HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5; }}
        .container {{ background-color: white; border-radius: 8px; padding: 30px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .header {{ text-align: center; padding-bottom: 20px; border-bottom: 2px solid #e0e0e0; margin-bottom: 30px; }}
        .header h1 {{ color: #1a73e8; margin: 0; font-size: 24px; }}
        .header p {{ color: #666; margin: 10px 0 0; }}
        .section {{ margin-bottom: 30px; }}
        .section-title {{ color: #1a73e8; font-size: 18px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid #e0e0e0; }}
        .post-suggestion {{ background-color: #f8f9fa; border-left: 4px solid #1a73e8; padding: 15px; margin: 10px 0; border-radius: 0 6px 6px 0; }}
        .platform-badge {{ display: inline-block; padding: 3px 10px; border-radius: 15px; font-size: 12px; font-weight: bold; margin-bottom: 10px; }}
        .twitter {{ background-color: #1da1f2; color: white; }}
        .linkedin {{ background-color: #0077b5; color: white; }}
        .post-content {{ white-space: pre-wrap; font-size: 14px; margin: 10px 0; }}
        .hashtags {{ color: #1a73e8; font-size: 13px; }}
        .tip {{ background-color: #e8f5e9; border-radius: 4px; padding: 10px; margin-top: 10px; font-size: 13px; }}
        .footer {{ text-align: center; padding-top: 20px; border-top: 1px solid #e0e0e0; margin-top: 30px; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📱 Social Media Content Digest</h1>
            <p>Your AI-powered content suggestions for {date}</p>
        </div>
        {content}
        <div class="footer">
            <p>Generated by Social Content Bot</p>
            <p>Powered by AI</p>
        </div>
    </div>
</body>
</html>
"""
    
    def __init__(self):
        cfg = get_config()
        self.smtp_server = cfg.email.smtp_server
        self.smtp_port = cfg.email.smtp_port
        self.smtp_username = cfg.email.smtp_username
        self.smtp_password = cfg.email.smtp_password
        self.email_from = cfg.email.email_from or cfg.email.smtp_username
        self.logger = get_logger()
        
        if not (self.smtp_username and self.smtp_password):
            console.print("[yellow]⚠[/yellow] SMTP credentials not fully configured")
        else:
            console.print(f"[green]✓[/green] Email sender configured for {self.smtp_server}:{self.smtp_port}")
    
    def create_email(self, to_email: str, subject: str, content_html: str, content_text: str = None) -> MIMEMultipart:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = self.email_from
        msg['To'] = to_email
        
        if content_text:
            msg.attach(MIMEText(content_text, 'plain'))
        
        msg.attach(MIMEText(content_html, 'html'))
        
        return msg
    
    @retry_with_backoff(exceptions=(smtplib.SMTPException, ConnectionRefusedError, OSError))
    def send_email(self, to_email: str, subject: str, content_html: str, content_text: str = None) -> bool:
        if not (self.smtp_username and self.smtp_password):
            raise ValueError("SMTP credentials not configured")
        
        msg = self.create_email(to_email, subject, content_html, content_text)
        
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), console=console) as progress:
            task = progress.add_task("Sending email...", total=None)
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)
            
            progress.update(task, description="Email sent successfully!")
        
        self.logger.info(f"Email sent to {to_email}")
        console.print(f"[green]✓[/green] Email sent to {to_email}")
        return True
    
    def format_digest_email(self, reddit_suggestions: List[Dict] = None, wordpress_suggestions: List[Dict] = None, reddit_items: List[Dict] = None, wordpress_items: List[Dict] = None) -> tuple:
        content_parts = []
        text_parts = []
        
        if reddit_suggestions:
            reddit_html = self._format_section_html("Reddit Upvotes", "🔥 Content ideas from your saved Reddit posts", reddit_suggestions, reddit_items)
            content_parts.append(reddit_html)
            text_parts.append(self._format_section_text("Reddit Upvotes", reddit_suggestions))
        
        if wordpress_suggestions:
            wp_html = self._format_section_html("Blog Posts", "✍️ Content ideas from your WordPress blog", wordpress_suggestions, wordpress_items)
            content_parts.append(wp_html)
            text_parts.append(self._format_section_text("Blog Posts", wordpress_suggestions))
        
        # Escape curly braces in content to avoid format() errors
        content_html_escaped = ''.join(content_parts).replace('{', '{{').replace('}', '}}') if content_parts else '<p>No content suggestions this time.</p>'
        
        html_content = self.HTML_TEMPLATE.format(
            date=datetime.now().strftime('%B %d, %Y'),
            content=content_html_escaped
        )
        
        text_content = '\n\n'.join(text_parts) if text_parts else 'No content suggestions this time.'
        
        return html_content, text_content
    
    def _format_section_html(self, title: str, subtitle: str, suggestions: List[Dict], original_items: List[Dict] = None) -> str:
        posts_html = []
        
        for suggestion in suggestions:
            platform = suggestion.get('platform', 'unknown')
            platform_class = 'twitter' if platform == 'twitter' else 'linkedin'
            platform_emoji = '🐦' if platform == 'twitter' else '💼'
            
            hashtags = suggestion.get('hashtags', [])
            hashtag_str = ' '.join(f'#{tag}' for tag in hashtags)
            
            post_html = f"""
            <div class="post-suggestion">
                <span class="platform-badge {platform_class}">{platform_emoji} {platform.upper()}</span>
                <div class="post-content">{suggestion.get('content', '')}</div>
                <div class="hashtags">{hashtag_str}</div>
                <div class="tip">
                    <strong>Tone:</strong> {suggestion.get('tone', 'N/A')}<br>
                    <strong>Tip:</strong> {suggestion.get('engagement_tip', 'N/A')}
                </div>
            </div>
            """
            posts_html.append(post_html)
        
        return f"""
        <div class="section">
            <h2 class="section-title">{title}</h2>
            <p style="color: #666; margin-bottom: 15px;">{subtitle}</p>
            {''.join(posts_html)}
        </div>
        """
    
    def _format_section_text(self, title: str, suggestions: List[Dict]) -> str:
        lines = [f"{'=' * 50}", f"{title}", f"{'=' * 50}"]
        
        for i, suggestion in enumerate(suggestions, 1):
            platform = suggestion.get('platform', 'unknown').upper()
            content = suggestion.get('content', '')
            hashtags = ' '.join(f'#{tag}' for tag in suggestion.get('hashtags', []))
            tone = suggestion.get('tone', 'N/A')
            tip = suggestion.get('engagement_tip', 'N/A')
            
            lines.extend([
                f"\n--- {platform} Post #{i} ---",
                content,
                f"\n{hashtags}",
                f"\nTone: {tone}",
                f"Tip: {tip}",
            ])
        
        return '\n'.join(lines)
    
    def send_digest(self, to_email: str = None, reddit_suggestions: List[Dict] = None, wordpress_suggestions: List[Dict] = None, reddit_items: List[Dict] = None, wordpress_items: List[Dict] = None) -> bool:
        cfg = get_config()
        to_email = to_email or cfg.email.email_to
        
        if not to_email:
            raise ValueError("Recipient email not configured. Set EMAIL_TO environment variable.")
        
        html_content, text_content = self.format_digest_email(
            reddit_suggestions=reddit_suggestions,
            wordpress_suggestions=wordpress_suggestions,
            reddit_items=reddit_items,
            wordpress_items=wordpress_items,
        )
        
        subject = f"📱 Social Media Content Digest - {datetime.now().strftime('%Y-%m-%d')}"
        
        return self.send_email(to_email, subject, html_content, text_content)